.MODEL SMALL

.CODE

MAIN PROC
       
    ;TAKE INPUT
    MOV AH,1       
    INT 21h   
    
    ;SAVE IT TO ANOTHER REGISTER
    ;OTHERWISE WHEN USING AH TO DISPLAY, THE DATA WILL GET LOST
    MOV BL,AL  
    
    ;NEW LINE AKA CARRIAGE RETURN
    ;EXECUTING CARRIAGE RETURN AND LINE FEED
    MOV AH,2
    MOV DL,0DH
    INT 21h
    MOV DL,0AH
    INT 21h  
           
    ;AND THEN DISPLAY
    MOV DL,BL
    INT 21h               
    
MAIN ENDP

END MAIN